development: &development
  adapter: postgresql
  database: nuboard-gallery_development
  encoding: utf8
test:
  <<: *development
  database: nuboard-gallery_test
production:
  <<: *development
  database: nuboard-gallery_production
staging:
  <<: *development
  database: nuboard-gallery_staging
